#!/usr/bin/env bash
# A script that Configure your Nginx server so that /redirect_me is redirecting to another page.

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html
string="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.adedoyin-emmanuel.netlify.app permanent;"
sudo sed -i "s/server_name _;/$string/" /etc/nginx/sites-enabled/default

sudo service nginx restart
