#!/usr/bin/env bash
# Bash script that generates a MySQL dump and creates a compressed archive out of it.
mysqldump -u root -p"$1" --all-databases > backup.sql
name=$(date '+%d-%m-%Y')
tar -cvzf "$name.tar.gz" backup.sql
