#!/usr/bin/env bash
#A Bash script that displays numbers from 1 to 100.
# Displays FizzBuzz when the number is a multiple of 3 and 5
# Displays Fizz when the number is multiple of 3
# Displays Buzz when the number is a multiple of 5
# Otherwise, displays the number
# In a list format
for ((i=1; i<100; i++))
do 
    if [ $((i % 3)) -eq 0 ] && [ $((i % 5)) -eq 0 ]
    then 
        echo "FizzBuzz"
    fi
    if [ $((i % 3)) -eq 0 ]
    then 
        echo "Fizz"
    fi
    if [ $((i % 5)) -eq 0 ]
    then
        echo "Buzz"
    fi
done
    
    
