#!/usr/bin/env bash
# Now that you’ve parsed the Apache log file, let’s sort the data so you can get a better idea of what is going on.

# Using what you did in the previous exercise, write a Bash script that groups visitors by IP and HTTP status code, and displays this data.

# Requirements:

# The exact format must be:
# OCCURENCE_NUMBER IP HTTP_CODE
# In list format
awk '{ print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn
