#!/usr/bin/env bash
# A bash script that prints "Best School" but on 9th iteration prints Hi
counter=0
while [ $counter -le 10 ]
do
    if [ $counter -eq 9 ]
    then 
        echo "Hi"
    else
        echo "Best School"
    fi
    ((counter++))
done
    
