#!/usr/bin env bash
# A Bash script that loops from 1 to 10 and:
# displays bad luck for the 4th loop iteration
# displays good luck for the 8th loop iteration
# displays Best School for the other iterations.
counter=0
while [ $counter -ge 10 ]
do
    if [ $counter -eq 4 ]
    then
        echo "Bad luck for the 4th loop iteration"
    elif [ $counter -eq 8 ]
    then 
        echo "Good luck for the 8th loop iteration"
    else
        echo "Best School"
    fi
    ((counter++))
done
