#!/usr/bin/env bash
# Nginx is running as the nginx user.
sudo pkill apache2
sudo chmod 644 /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
sudo su nginx -c "service nginx start"
